#!/bin/sh

DIR=$(cd "$(dirname "$0")"; pwd)
MONO_FRAMEWORK_PATH=/Library/Frameworks/Mono.framework/Versions/Current
export DYLD_FALLBACK_LIBRARY_PATH="$DIR:$MONO_FRAMEWORK_PATH/lib:/lib:/usr/lib"
export PATH="$MONO_FRAMEWORK_PATH/bin:$PATH"

# Mono version check
REQUIRED_MAJOR=5
REQUIRED_MINOR=0

MONO_VERSION="$(mono --version | grep 'Mono JIT compiler version ' | cut -f5 -d\ )"
MONO_VERSION_MAJOR="$(echo $MONO_VERSION | cut -f1 -d.)"
MONO_VERSION_MINOR="$(echo $MONO_VERSION | cut -f2 -d.)"

VERSION_TITLE="Cannot launch Super Ping Pong"
VERSION_MSG="Super Ping Pong requires the Mono Framework version $REQUIRED_MAJOR.$REQUIRED_MINOR or later."
DOWNLOAD_URL="http://www.mono-project.com/download/"

if [ -z "$MONO_VERSION" ] \
	|| [ $MONO_VERSION_MAJOR -lt $REQUIRED_MAJOR ] \
	|| [ $MONO_VERSION_MAJOR -eq $REQUIRED_MAJOR -a $MONO_VERSION_MINOR -lt $REQUIRED_MINOR ]
then
	osascript \
	-e "set question to display dialog \"$VERSION_MSG\" with title \"$VERSION_TITLE\" buttons {\"Cancel\", \"Download...\"} default button 2" \
	-e "if button returned of question is equal to \"Download...\" then do shell script \"open \\\"$DOWNLOAD_URL\\\"\""
	echo "$VERSION_TITLE"
	echo "$VERSION_MSG"
	exit 1
fi

LOG_FILE="$HOME/Library/Logs/SuperPong/SuperPong.log"
mkdir -p "`dirname \"$LOG_FILE\"`"

exec -a "SuperPong" mono "$DIR/SuperPong.exe" $* 2>&1 1> "$LOG_FILE"
